### ISSUE TITLE
Revisit naming rules

### ISSUE THREAD

**Issue by reyang** [census-instrumentation/opencensus-python#364]
This is to follow up on #362.

More details will be added.

**Comment by c24t** [comment]
@reyang I think this one is fixed, anything else to add here?

**Comment by reyang** [comment]
We still have something weird, for example `async_.py`.
But let's close this one and try to address the other naming issues (also import pattern) when we add pylint next week.
